config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :resources, :videos, :music do
    collection do
      post :destroy_multiple
    end
  end

  delete 'music/destroy_upload/:name', to: 'music#destroy_upload'
  delete 'videos/destroy_upload/:name', to: 'videos#destroy_upload'
  get 'access_denied', to: 'resources#access_denied'
  root 'resources#home'
end

app/views/resources/access_denied.html.erb
<% provide(:title, "Access_Denied") %>
<div class="container">
  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="well">
        <h4><strong>Sorry, you are not authorized. Please contact system administrators at <%= mail_to "cfu-liblts@wustl.edu" %></strong></h4>
      </div>
    </div>
  </div>
</div>

app/views/resources/edit.html.erb
<div class="container">
  <h1>Update Resource</h1>

  <%= form_with(model: @resource, local: true) do |form| %>

    <% if @resource.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@resource.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label 'Item#' %><br>
      <%= form.text_field :item_id %>
    </p>

    <p>
      <%= form.submit class: 'btn btn-primary' %>
    </p>
  <% end %>

  <%= link_to 'Back', resources_path, class: 'btn btn-default' %>
</div>

app/views/resources/home.html.erb
<% provide(:title, "Home") %>
<div class="container">
  <div class="center jumbotron">
    <h1>Welcome to WashU Stream</h1>
    <h3>
      University Libraries Streaming Reserves
    </h3>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Upload Manager</h3>
        </div>
        <div class="panel-body">
          <p>Upload video files for streaming.</p>
          <% if current_user[:group] == 'superadmin' %>
            <p><%= link_to "Upload Music", new_music_path, :class => "btn btn-default" %></p>
            <p><%= link_to "Upload Video", new_video_path, :class => "btn btn-default" %></p>
          <% elsif current_user[:group] == 'mradmin' %>
            <p><%= link_to "Upload Music", new_music_path, :class => "btn btn-default" %></p>
          <% elsif current_user[:group] == 'sradmin' %>
            <p><%= link_to "Upload Video", new_video_path, :class => "btn btn-default" %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Reserves Manager</h3>
        </div>
        <div class="panel-body">
          <p>Manage and review list of streaming reserves</p>
          <% if current_user[:group] == 'superadmin' %>
            <p><%= link_to "All", resources_path, :class => "btn btn-default" %></p>
            <p><%= link_to "Music", music_index_path, :class => "btn btn-default" %></p>
            <p><%= link_to "Video", videos_path, :class => "btn btn-default" %></p>
          <% elsif current_user[:group] == 'mradmin' %>
            <p><%= link_to "Music", music_index_path, :class => "btn btn-default" %></p>
          <% elsif current_user[:group] == 'sradmin' %>
            <p><%= link_to "Video", videos_path, :class => "btn btn-default" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<% provide(:title, "Resources") %>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h4>All Reserves</h4></div>
  <div class="panel-body">
    <p>
    <form class="form-inline" action="/resources" method="get" id="search-form">
      <label class="sr-only" for="search">Name</label>
      <input type="text" class="form-control mb-2 mr-sm-2" id="search" name="search" placeholder="Search Resources">
      <button type="submit" class="btn btn-warning">Search</button>
    </form>
    </p>
    <form action="/resources/destroy_multiple" method="post" %>
      <table class="table">
        <tr>
          <th><input type="checkbox" class="checkAll" name="checkAll" /></th>
          <th><%= sortable "item_id", "ItemID" %></th>
          <th><%= sortable "title", "Title" %></th>
          <th><%= sortable "subtitles", "Subtitles" %></th>
          <th><%= sortable "course_id", "CourseID" %></th>
          <th><%= sortable "course_name", "Course Name" %></th>
          <th><%= sortable "semester", "Semester" %></th>
          <th><%= sortable "instructor", "Instructor" %></th>
          <th><%= sortable "content_type", "Content Type" %></th>
          <th>URL</th>
          <th>Delete</th>
        </tr>
        <% for resource in @resources %>
          <tr>
            <td><%= check_box_tag "resource_ids[]", resource.id %></td>
            <td><%= resource.item_id %></td>
            <td><%= resource.title.titleize %></td>
            <td><%= resource.subtitles %></td>
            <td><%= resource.course_id %></td>
            <td><%= resource.course_name %></td>
            <td><%= resource.semester %></td>
            <td><%= resource.instructor %></td>
            <td><%= resource.content_type %></td>
            <td>
              <% if resource.content_type == 'music' %>
                <button type="button" class="btn btn-info" onclick="window.prompt('Press Ctrl-C to copy URL', 'http://' + '<%= Figaro.env.request_host %>' + '<%= music_path(resource).to_s %>')">Show URL</button>
              <% elsif resource.content_type == 'video' %>
                <button type="button" class="btn btn-info" onclick="window.prompt('Press Ctrl-C to copy URL','http://' + '<%= Figaro.env.request_host %>' + '<%= video_path(resource).to_s %>')">Show URL</button>
              <% else %>
                <button type="button" class="btn btn-info" onclick="window.prompt('Press Ctrl-C to copy URL','http://' + '<%= Figaro.env.request_host %>' + '<%= resource_path(resource).to_s %>')">Show URL</button>
              <% end %>
            </td>
            <td>
              <%= link_to 'Delete', resource_path(resource), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= submit_tag "Delete Checked", class: "btn btn-primary", data: {confirm: 'Are you sure?'} %>
    </form>
  </div>
  <div class="text-center">
    <% if @resources %>
      <%= will_paginate @resources %>
    <% end %>
  </div>
</div>

app/views/resources/music_index.html.erb
<% provide(:title, "Resources") %>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h4>Reserves</h4></div>
  <div class="panel-body">
    <p>
    <form class="form-inline" action="/music_admin" method="get" id="search-form">
      <label class="sr-only" for="search">Name</label>
      <input type="text" class="form-control mb-2 mr-sm-2" id="search" name="search" placeholder="Search Resources">
      <button type="submit" class="btn btn-warning">Search</button>
    </form>
    </p>
    <form action="/resources/destroy_multiple" method="post" %>
      <table class="table">
        <tr>
          <th><input type="checkbox" class="checkAll" name="checkAll" /></th>
          <th><%= sortable "item_id", "ItemID" %></th>
          <th><%= sortable "title", "Title" %></th>
          <th><%= sortable "subtitles", "Subtitles" %></th>
          <th><%= sortable "course_id", "CourseID" %></th>
          <th><%= sortable "course_name", "Course Name" %></th>
          <th><%= sortable "semester", "Semester" %></th>
          <th><%= sortable "instructor", "Instructor" %></th>
          <th>URL</th>
          <th>Delete</th>
        </tr>
        <% for resource in @resources %>
          <tr>
            <td><%= check_box_tag "resource_ids[]", resource.id %></td>
            <td><%= resource.item_id %></td>
            <td><%= resource.title.titleize %></td>
            <td><%= resource.subtitles %></td>
            <td><%= resource.course_id %></td>
            <td><%= resource.course_name %></td>
            <td><%= resource.semester %></td>
            <td><%= resource.instructor %></td>
            <td><%= "http://#{request.host}:3000" + resource_path(resource).to_s %></td>
            <td>
              <button type="button" class="btn btn-primary"><%= link_to 'Delete', resource_path(resource), method: :delete, data: {confirm: 'Are you sure?'} %></button>
            </td>
          </tr>
        <% end %>
      </table>
      <button type="submit" class="btn btn-primary">Delete Checked</button>
    </form>
  </div>
  <div class="text-center">
    <% if @resources %>
      <%= will_paginate @resources %>
    <% end %>
  </div>
</div>

app/views/resources/music_upload.html.erb
<div class="container">
  <!-- The file upload form used as target for the file upload widget -->
  <form id="music_fileupload" method="POST" enctype="multipart/form-data">
    <!-- Redirect browsers with JavaScript disabled to the origin page -->
<!--    <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>-->
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="col-lg-7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="resource[video]" multiple>
                </span>
        <button type="submit" class="btn btn-primary start">
          <i class="glyphicon glyphicon-upload"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="glyphicon glyphicon-ban-circle"></i>
          <span>Cancel upload</span>
        </button>
        <!-- The global file processing state -->
        <span class="fileupload-process"></span>
      </div>
      <!-- The global progress state -->
      <div class="col-lg-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
      </div>
    </div>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
  </form>
  <br>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
{% } %}
</script>

app/views/resources/new.html.erb
<div class="container">
  <!-- The file upload form used as target for the file upload widget -->
  <form id="fileupload" method="POST" enctype="multipart/form-data">
    <!-- Redirect browsers with JavaScript disabled to the origin page -->
<!--    <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>-->
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="col-lg-7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="resource[video]" multiple>
                </span>
        <button type="submit" class="btn btn-primary start">
          <i class="glyphicon glyphicon-upload"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="glyphicon glyphicon-ban-circle"></i>
          <span>Cancel upload</span>
        </button>
        <!-- The global file processing state -->
        <span class="fileupload-process"></span>
      </div>
      <!-- The global progress state -->
      <div class="col-lg-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
      </div>
    </div>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
  </form>
  <br>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>

app/views/resources/show.html.erb
<% provide(:title, "Video") %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @resource.title %></h1>
      <p>Course: <%= @resource.course_name %></p>
      <p>Instructor: <%= @resource.instructor %></p>
      <p>
      <div id="player"></div>
        <script>
            jwplayer("player").setup({
                playlist: [{
                    sources: [{
                        file: "rtmp://<%= Figaro.env.wowza_server =%>/reserves/<%= @resource.item_id %>.<%= @resource.content_type %>"
                    }, {
                        file: "http://<%= Figaro.env.wowza_server =%>/reserves/<%= @resource.content_type %>:<%= @resource.item_id %>.<%= @resource.content_type %>/playlist.m3u8"
                    }]
                }],
                mediaid: "<%= @resource.media_id %>"
                ,
                rtmp: {
                    bufferlength: 3
                },
                fallback: true
            });
        </script>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>Copyright Statement</h1>
      <p>This service is available for Washington University instructors and students only to be used in conjunction
        with course reserves. Material is subject to the copyright law of the United States (Title 17, U.S. Code).
        Individuals are prohibited from downloading, sharing, installing, and/or operating unauthorized media programs,
        applications, and devices in accordance with the Washington University Computer Use Policy, and any misconduct
        is subject to disciplinary action under the Student Judicial Code.</p>
    </div>
  </div>
</div>